[package]
name = "frost-codegen"
version = "0.1.2"
edition = "2021"
rust-version = "1.65"

[dependencies]
chumsky = "0.8.0"
bpaf = { workspace = true }
frost = {path = "../frost"}
lazy_static = "1.4.0"
serde = { workspace = true, features = ["derive"]}
serde-xml-rs = "0.6.0"
walkdir = "2.3.2"
