[package]
name = "frost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "frost"
path = "src/lib.rs"

[[bin]]
name = "frostinfo"
path = "src/bin.rs"

[dev-dependencies]
tempfile = "3"

