[workspace]

members = [
    "examples/read_bag",
    "frost",
    "frost-codegen"
]

[profile.release]
lto = true

[workspace.dependencies]
bpaf = "0.7.1"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_rosmsg = "0.2.0"
tempfile = "3.3.0"