[workspace]

members = [
    "examples/read_bag",
    "frost",
    "frost-codegen"
]

[profile.release]
lto = true
codegen-units = 1

[workspace.dependencies]
bpaf = "0.9.8"
serde = "1.0.193"
serde_rosmsg = "0.2.0"
tempfile = "3.3.0"