[package]
name = "frost"
version = "0.1.2"
edition = "2021"

[lib]
name = "frost"
path = "src/lib.rs"

[[bin]]
name = "frost"
path = "src/bin/frost.rs"

[dev-dependencies]
tempfile = "3.3.0"

[dependencies]
bpaf = "0.5.7"
chrono = "0.4.22"
itertools = "0.10.3"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_rosmsg = "0.2.0"
