on:
  pull_request:
  push:
    branches:
      - master


name: Check and Lint

jobs:
  check:
    name: Check linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-targets

      - uses: actions-rs/cargo@v1
        name: all features
        with:
          command: test
          args: --workspace --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: all features
        with:
          command: test
          args: --workspace --doc --all-features


  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
