on:
  pull_request:
  push:
    branches:
      - master


name: Check and Lint

jobs:
  windows:
    runs-on: windows-latest
    name: Check windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-targets

      - uses: actions-rs/cargo@v1
        name: all features
        with:
          command: test
          args: --workspace --all-targets --all-features

  check:
    name: Check linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace --all-targets

      - uses: actions-rs/cargo@v1
        name: all features
        with:
          command: test
          args: --workspace --all-targets --all-features

      - uses: actions-rs/cargo@v1
        name: all features
        with:
          command: test
          args: --workspace --doc --all-features

      - name: example documentation
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features -p docs

      - name: should not have any changes
        run: git diff && git diff-index --quiet HEAD --

      - name: Rustdoc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --no-deps --all-features
        env:
          RUSTDOCFLAGS: '-D warnings'

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - run: echo "" > docs/src/lib.rs
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
